name: New Submission
description: Select this to submit new Algorithm/Data-Structure/STL/...
title: "Title of the Submission"
labels: ["Hacktoberfest", "new submission", "first timer", "good first issue"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        I have verified that this issue doesn't already exist.
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Type of the submission
      options:
        - Algorithm
        - Data-Structure
        - Maths
        - STL
        - Collection
    validations:
      required: true
  - type: input
    id: directory
    attributes:
      label: Directory
      description: Location of the new file
      placeholder: Algorithm => Sorting => Merge-Sort => Merge-Sort.ext
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the submission
      placeholder: A linked list is a linear collection of data elements whose ...
    validations:
      required: true
  - type: checkboxes
    id: language
    attributes:
      label: Programming Language
      description: programming language
      options:
        - label: c++
        - label: c
        - label: python
        - label: java
        - label: kotlin
        - label: javascript
        - label: typescript
        - label: c#
        - label: swift
        - label: ruby
        - label: scala
        - label: go
        - label: php
        - label: haskell
        - label: bash
